### ISSUE TITLE
Does this project have persistence support?

### ISSUE THREAD

**Issue by alisher-matkurbanov** [telebotter/django-telegrambot#5]
Thank you for upgrading this project!
I'm gonna migrate my current project and need [persistence](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent) feature from python-telegram-bot in my project. 
Does it support this feature?

**Comment by lukruh** [comment]
Since this module wraps the ptb package, in principle all ptb features should be usable. I've not used the PicklePersistance yet, because I always use django models to keep the data I need persistant. But through django you can work with files such as you can in a plain python script. Just care about permissions, the django code is run by the `www-data` user (at least on a usual linux server).

**Comment by alisher-matkurbanov** [comment]
@lukruh Thanks, I'll try and add info in the future. I think this issue may be closed.
